<?php
/* ELAK CORE Akilli Rehber Mobile Bridge v1.0 - PHP 5.6+ */
error_reporting(E_ALL);
ini_set('display_errors','0');
ini_set('log_errors','1');

require dirname(__FILE__).'/db.php';

function cr_https(){return (!empty($_SERVER['HTTPS'])&&strtolower($_SERVER['HTTPS'])!=='off')||(!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])&&strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])==='https');}
function cr_clean($v,$n){$v=trim((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n,'UTF-8'):substr($v,0,$n);}
function cr_now(){return date('Y-m-d H:i:s');}
function cr_send($d,$status){http_response_code($status);header('Content-Type: application/json; charset=UTF-8');header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('Pragma: no-cache');header('X-Content-Type-Options: nosniff');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function cr_ok($d){if(!is_array($d))$d=array();$d['ok']=true;cr_send($d,200);}
function cr_err($m,$s){cr_send(array('ok'=>false,'error'=>$m),$s);}
function cr_body(){$raw=file_get_contents('php://input');if($raw===false||trim($raw)==='')return array();$d=json_decode($raw,true);if(!is_array($d))cr_err('Geçersiz istek verisi.',400);return $d;}
function cr_auth_header(){if(!empty($_SERVER['HTTP_AUTHORIZATION']))return trim($_SERVER['HTTP_AUTHORIZATION']);if(!empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION']))return trim($_SERVER['REDIRECT_HTTP_AUTHORIZATION']);return '';}
function cr_bearer(){$h=cr_auth_header();if(preg_match('/^Bearer\s+([A-Za-z0-9,-]{16,160})$/i',$h,$m))return $m[1];return '';}
function cr_session_start($token){session_name('ELAKCORESESSID');session_set_cookie_params(0,'/','',cr_https(),true);if($token!==''){@session_id($token);}@session_start();}
function cr_json_array($v){if(is_array($v))return $v;$x=json_decode((string)$v,true);return is_array($x)?$x:array();}
function cr_module_ok($org){$mods=cr_json_array(isset($org['modules'])?$org['modules']:array());if(!count($mods))return true;return in_array('akilli_rehber',$mods,true)||in_array('rehber',$mods,true);}
function cr_license_ok($o){return $o&&!empty($o['status'])&&!empty($o['expiry'])&&strtotime($o['expiry'])>=time()&&cr_module_ok($o);}
function cr_org_by_code($code){$q=elak_db()->prepare('SELECT * FROM `'.elak_table('organizations').'` WHERE org_code=? LIMIT 1');$q->execute(array($code));return $q->fetch();}
function cr_has($k){if(!empty($_SESSION['legacy_org_admin']))return true;$p=isset($_SESSION['permissions'])&&is_array($_SESSION['permissions'])?$_SESSION['permissions']:array();return !empty($p['*'])||!empty($p[$k]);}
function cr_can_edit(){return cr_has('users.manage')||cr_has('settings.manage');}
function cr_require(){if(empty($_SESSION['org_id']))cr_err('Oturum süresi dolmuş. ELAK Okulum üzerinden tekrar giriş yapın.',401);$q=elak_db()->prepare('SELECT * FROM `'.elak_table('organizations').'` WHERE id=? LIMIT 1');$q->execute(array((int)$_SESSION['org_id']));$o=$q->fetch();if(!cr_license_ok($o))cr_err('Kurum lisansı veya Akıllı Rehber modülü aktif değil.',403);if(!empty($_SESSION['user_id'])){$q=elak_db()->prepare('SELECT active FROM `'.elak_table('users').'` WHERE id=? AND org_id=? LIMIT 1');$q->execute(array((int)$_SESSION['user_id'],(int)$_SESSION['org_id']));if((int)$q->fetchColumn()!==1)cr_err('Kullanıcı hesabı pasif.',403);$rk=isset($_SESSION['role_key'])?(string)$_SESSION['role_key']:'';$allowed=in_array($rk,array('admin','manager','teacher','guidance'),true)||cr_has('users.view')||cr_has('settings.view');if(!$allowed)cr_err('Akıllı Rehber erişim yetkiniz yok.',403);}return $o;}
function cr_phone($v){$d=preg_replace('/\D+/','',(string)$v);if(strlen($d)>=12&&substr($d,0,2)==='90')$d=substr($d,2);if(strlen($d)===11&&substr($d,0,1)==='0')$d=substr($d,1);return substr($d,0,20);}
function cr_photo_root(){return dirname(__FILE__).'/storage/student-photos';}
function cr_photo_abs($rel){$rel=str_replace(array('..','\\'),'',(string)$rel);return cr_photo_root().'/'.$rel;}
function cr_photo_info($path){$i=@getimagesize($path);if(!$i||empty($i[2]))return null;if($i[2]===IMAGETYPE_JPEG)return array('ext'=>'jpg','mime'=>'image/jpeg');if($i[2]===IMAGETYPE_PNG)return array('ext'=>'png','mime'=>'image/png');return null;}
function cr_photo_dir($org){$root=cr_photo_root();if(!is_dir($root)&&!@mkdir($root,0755,true))cr_err('Fotoğraf klasörü oluşturulamadı.',500);$deny=$root.'/.htaccess';if(!is_file($deny))@file_put_contents($deny,"Deny from all\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n",LOCK_EX);$d=$root.'/'.(int)$org;if(!is_dir($d)&&!@mkdir($d,0755,true))cr_err('Kurum fotoğraf klasörü oluşturulamadı.',500);return $d;}
function cr_revision($org){$db=elak_db();$max='';$queries=array(
 'SELECT MAX(updated_at) FROM `'.elak_table('data_classes').'` WHERE org_id=?',
 'SELECT MAX(updated_at) FROM `'.elak_table('data_students').'` WHERE org_id=?',
 'SELECT MAX(updated_at) FROM `'.elak_table('data_guardians').'` WHERE org_id=?',
 'SELECT MAX(updated_at) FROM `'.elak_table('data_student_guardians').'` WHERE org_id=?'
 );foreach($queries as $sql){try{$q=$db->prepare($sql);$q->execute(array($org));$v=(string)$q->fetchColumn();if($v!==''&&($max===''||$v>$max))$max=$v;}catch(Exception $e){}}return $max!==''?(string)strtotime($max):'0';}
function cr_announcements($org){try{$now=cr_now();$sql='SELECT id,title,body,level,created_at FROM `'.elak_table('announcements').'` WHERE active=1 AND (org_id IS NULL OR org_id=?) AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>=?) ORDER BY id DESC LIMIT 20';$q=elak_db()->prepare($sql);$q->execute(array($org,$now,$now));$out=array();foreach($q->fetchAll() as $r){$body=(string)$r['body'];$summary=function_exists('mb_substr')?mb_substr($body,0,220,'UTF-8'):substr($body,0,220);$out[]=array('id'=>(string)$r['id'],'title'=>$r['title'],'summary'=>$summary,'body'=>$body,'published_at'=>$r['created_at'],'priority'=>isset($r['level'])?$r['level']:'info');}return $out;}catch(Exception $e){return array();}}
function cr_user_payload(){return array('id'=>!empty($_SESSION['user_id'])?(int)$_SESSION['user_id']:0,'display_name'=>isset($_SESSION['user_name'])?$_SESSION['user_name']:'Kurum Yöneticisi','name'=>isset($_SESSION['user_name'])?$_SESSION['user_name']:'Kurum Yöneticisi','role'=>isset($_SESSION['role_name'])?$_SESSION['role_name']:'Kurum Yöneticisi','role_key'=>isset($_SESSION['role_key'])?$_SESSION['role_key']:'admin');}
function cr_bundle($org){
 $db=elak_db();$ct=elak_table('data_classes');$st=elak_table('data_students');$gt=elak_table('data_guardians');$sgt=elak_table('data_student_guardians');
 $q=$db->prepare('SELECT c.id,c.name,c.grade_level,c.branch,c.school_type,(SELECT COUNT(*) FROM `'.$st.'` s WHERE s.org_id=c.org_id AND s.class_id=c.id AND s.active=1) student_count FROM `'.$ct.'` c WHERE c.org_id=? AND c.active=1 ORDER BY CAST(c.grade_level AS UNSIGNED),c.name');$q->execute(array($org));$classes=array();foreach($q->fetchAll() as $c){$classes[]=array('class_id'=>(int)$c['id'],'id'=>(int)$c['id'],'name'=>$c['name'],'class_name'=>$c['name'],'grade'=>(string)$c['grade_level'],'grade_level'=>(string)$c['grade_level'],'branch'=>(string)$c['branch'],'school_type'=>(string)$c['school_type'],'whatsapp_group_url'=>'','is_class_teacher'=>false,'student_count'=>(int)$c['student_count']);}
 $q=$db->prepare('SELECT sg.student_id,g.id guardian_id,g.full_name,g.phone,sg.relationship,sg.is_primary FROM `'.$sgt.'` sg INNER JOIN `'.$gt.'` g ON g.id=sg.guardian_id AND g.org_id=sg.org_id WHERE sg.org_id=? AND g.active=1 ORDER BY sg.student_id,sg.is_primary DESC,sg.id');$q->execute(array($org));$gmap=array();foreach($q->fetchAll() as $g){$sid=(int)$g['student_id'];if(!isset($gmap[$sid]))$gmap[$sid]=array();$gmap[$sid][]=array('id'=>(int)$g['guardian_id'],'guardian_id'=>(int)$g['guardian_id'],'name'=>$g['full_name'],'guardian_name'=>$g['full_name'],'relationship'=>$g['relationship'],'phone'=>cr_phone($g['phone']),'is_primary'=>(int)$g['is_primary']?true:false);}
 $q=$db->prepare('SELECT s.id,s.school_no,s.full_name,s.class_id,c.name class_name,s.school_type,s.gender,s.boarding_status,s.phone,s.photo_path,s.photo_updated_at FROM `'.$st.'` s LEFT JOIN `'.$ct.'` c ON c.id=s.class_id AND c.org_id=s.org_id WHERE s.org_id=? AND s.active=1 ORDER BY c.name,s.full_name');$q->execute(array($org));$students=array();$entries=array();$editable=cr_can_edit();foreach($q->fetchAll() as $s){$sid=(int)$s['id'];$pv=!empty($s['photo_updated_at'])?strtotime($s['photo_updated_at']):0;$guardians=isset($gmap[$sid])?$gmap[$sid]:array();$item=array('student_id'=>$sid,'id'=>$sid,'student_name'=>$s['full_name'],'name'=>$s['full_name'],'full_name'=>$s['full_name'],'school_no'=>$s['school_no'],'class_id'=>!empty($s['class_id'])?(int)$s['class_id']:0,'class_name'=>isset($s['class_name'])?(string)$s['class_name']:'','student_phone'=>cr_phone($s['phone']),'phone'=>cr_phone($s['phone']),'school_type'=>(string)$s['school_type'],'gender'=>(string)$s['gender'],'boarding_status'=>(string)$s['boarding_status'],'has_photo'=>!empty($s['photo_path']),'photo_version'=>$pv,'can_edit'=>$editable,'guardians'=>$guardians);$students[]=$item;
   $studentObj=array('id'=>$sid,'student_id'=>$sid,'name'=>$s['full_name'],'school_no'=>$s['school_no'],'class_name'=>$item['class_name'],'phone'=>$item['student_phone'],'has_photo'=>$item['has_photo'],'photo_version'=>$pv);
   if(strlen($item['student_phone'])>=10){$entries[]=array('phone'=>$item['student_phone'],'label'=>'Öğrenci','student_id'=>$sid,'student_name'=>$s['full_name'],'school_no'=>$s['school_no'],'class_name'=>$item['class_name'],'relationship'=>'Öğrenci','guardian_name'=>'','has_photo'=>$item['has_photo'],'photo_version'=>$pv,'student'=>$studentObj);}
   foreach($guardians as $g){if(strlen($g['phone'])<10)continue;$entries[]=array('phone'=>$g['phone'],'label'=>$g['relationship'],'student_id'=>$sid,'student_name'=>$s['full_name'],'school_no'=>$s['school_no'],'class_name'=>$item['class_name'],'relationship'=>$g['relationship'],'guardian_name'=>$g['name'],'has_photo'=>$item['has_photo'],'photo_version'=>$pv,'student'=>$studentObj,'guardian'=>array('id'=>$g['id'],'name'=>$g['name'],'relationship'=>$g['relationship'],'phone'=>$g['phone']));}
 }
 return array('students_summary'=>$students,'students'=>$students,'classes'=>$classes,'entries'=>$entries,'announcements'=>cr_announcements($org),'revision'=>cr_revision($org),'user'=>cr_user_payload(),'school_scope'=>'both','mobile_access'=>'both','source'=>'ELAK Kurum Veri Merkezi');
}
function cr_login($in){$db=elak_db();$code=strtoupper(cr_clean(isset($in['code'])?$in['code']:(isset($in['org_code'])?$in['org_code']:''),80));$username=cr_clean(isset($in['username'])?$in['username']:'',100);$pass=isset($in['password'])?(string)$in['password']:'';if($pass==='')cr_err('Şifre zorunludur.',400);$chosen=null;$user=null;
 if($code!==''){$org=cr_org_by_code($code);if(!cr_license_ok($org))cr_err('Kurum bulunamadı, lisansı pasif veya Akıllı Rehber modülü kapalı.',403);if($username===''){if(empty($org['org_password_hash'])||!password_verify($pass,$org['org_password_hash']))cr_err('Kurum şifresi hatalı.',401);$chosen=$org;}else{$sql='SELECT u.*,r.role_key,r.role_name,r.permissions FROM `'.elak_table('users').'` u INNER JOIN `'.elak_table('roles').'` r ON r.id=u.role_id WHERE u.org_id=? AND u.username=? LIMIT 1';$q=$db->prepare($sql);$q->execute(array((int)$org['id'],$username));$u=$q->fetch();if(!$u||empty($u['active'])||!password_verify($pass,$u['password_hash']))cr_err('Kullanıcı adı veya şifre hatalı.',401);$chosen=$org;$user=$u;}}
 else{if($username==='')cr_err('Kurum kodu veya kullanıcı adı gereklidir.',400);$sql='SELECT u.*,r.role_key,r.role_name,r.permissions,o.org_name,o.org_code,o.status,o.expiry,o.modules,o.org_password_hash FROM `'.elak_table('users').'` u INNER JOIN `'.elak_table('roles').'` r ON r.id=u.role_id INNER JOIN `'.elak_table('organizations').'` o ON o.id=u.org_id WHERE u.username=? AND u.active=1';$q=$db->prepare($sql);$q->execute(array($username));$matches=array();foreach($q->fetchAll() as $u){if(!password_verify($pass,$u['password_hash']))continue;$org=array('id'=>$u['org_id'],'org_name'=>$u['org_name'],'org_code'=>$u['org_code'],'status'=>$u['status'],'expiry'=>$u['expiry'],'modules'=>$u['modules'],'org_password_hash'=>$u['org_password_hash']);if(!cr_license_ok($org))continue;$matches[]=array($org,$u);}if(count($matches)===0)cr_err('Kullanıcı adı veya şifre hatalı.',401);if(count($matches)>1)cr_err('Bu kullanıcı adı birden fazla kurumda bulunuyor. Kurum kodu ile giriş yapın.',409);$chosen=$matches[0][0];$user=$matches[0][1];}
 @session_regenerate_id(true);$_SESSION['org_id']=(int)$chosen['id'];$_SESSION['user_id']=$user?(int)$user['id']:null;$_SESSION['role_key']=$user?$user['role_key']:'admin';$_SESSION['role_name']=$user?$user['role_name']:'Kurum Yöneticisi';$_SESSION['permissions']=$user?cr_json_array($user['permissions']):array('*'=>true);$_SESSION['user_name']=$user?$user['full_name']:'Kurum Yöneticisi';$_SESSION['legacy_org_admin']=$user?false:true;$_SESSION['rehber_mobile']=1;$_SESSION['rehber_login_at']=time();
 if($user){try{$q=$db->prepare('UPDATE `'.elak_table('users').'` SET last_login=?,updated_at=? WHERE id=?');$q->execute(array(cr_now(),cr_now(),(int)$user['id']));}catch(Exception $e){}}
 cr_ok(array('token'=>session_id(),'name'=>$_SESSION['user_name'],'display_name'=>$_SESSION['user_name'],'role'=>$_SESSION['role_name'],'school_scope'=>'both','org_code'=>$chosen['org_code'],'user'=>cr_user_payload(),'data'=>array('token'=>session_id(),'name'=>$_SESSION['user_name'],'display_name'=>$_SESSION['user_name'],'role'=>$_SESSION['role_name'],'school_scope'=>'both','org_code'=>$chosen['org_code'],'user'=>cr_user_payload())));
}

$api=isset($_GET['api'])?cr_clean($_GET['api'],50):'status';
$bearer=cr_bearer();cr_session_start($bearer);
try{
 if($api==='status')cr_ok(array('service'=>'ELAK CORE Akıllı Rehber Bridge','version'=>'1.0','source'=>'Kurum Veri Merkezi'));
 if($api==='login'){if($_SERVER['REQUEST_METHOD']!=='POST')cr_err('POST gerekli.',405);cr_login(cr_body());}
 $orgRow=cr_require();$org=(int)$orgRow['id'];
 if($api==='sync'){cr_ok(array('data'=>cr_bundle($org)));}
 if($api==='revision'){cr_ok(array('data'=>array('revision'=>cr_revision($org)),'revision'=>cr_revision($org)));}
 if($api==='change_summary'){$since=cr_clean(isset($_GET['since'])?$_GET['since']:'',80);$rev=cr_revision($org);cr_ok(array('data'=>array('revision'=>$rev,'changed'=>$since===''||$since!==$rev),'revision'=>$rev,'changed'=>$since===''||$since!==$rev));}
 if($api==='student_detail'){$id=(int)(isset($_GET['id'])?$_GET['id']:0);$bundle=cr_bundle($org);$found=null;foreach($bundle['students_summary'] as $s){if((int)$s['student_id']===$id){$found=$s;break;}}if(!$found)cr_err('Öğrenci bulunamadı.',404);cr_ok(array('data'=>array('student'=>$found),'student'=>$found));}
 if($api==='student_update'){if($_SERVER['REQUEST_METHOD']!=='POST')cr_err('POST gerekli.',405);if(!cr_can_edit())cr_err('Öğrenci bilgilerini düzenleme yetkiniz yok.',403);$in=cr_body();$sid=(int)(isset($in['student_id'])?$in['student_id']:0);if(!$sid)cr_err('Öğrenci seçilmedi.',400);$db=elak_db();$q=$db->prepare('SELECT id FROM `'.elak_table('data_students').'` WHERE org_id=? AND id=? AND active=1 LIMIT 1');$q->execute(array($org,$sid));if(!$q->fetchColumn())cr_err('Öğrenci bulunamadı.',404);$phone=cr_phone(isset($in['student_phone'])?$in['student_phone']:'');$db->prepare('UPDATE `'.elak_table('data_students').'` SET phone=?,updated_at=? WHERE org_id=? AND id=?')->execute(array($phone,cr_now(),$org,$sid));$guards=isset($in['guardians'])&&is_array($in['guardians'])?$in['guardians']:array();foreach($guards as $g){$gid=(int)(isset($g['id'])?$g['id']:0);if(!$gid)continue;$q=$db->prepare('SELECT g.id FROM `'.elak_table('data_guardians').'` g INNER JOIN `'.elak_table('data_student_guardians').'` sg ON sg.guardian_id=g.id AND sg.org_id=g.org_id WHERE g.org_id=? AND g.id=? AND sg.student_id=? LIMIT 1');$q->execute(array($org,$gid,$sid));if(!$q->fetchColumn())continue;$name=cr_clean(isset($g['name'])?$g['name']:'',180);$gp=cr_phone(isset($g['phone'])?$g['phone']:'');if($name!=='')$db->prepare('UPDATE `'.elak_table('data_guardians').'` SET full_name=?,phone=?,updated_at=? WHERE org_id=? AND id=?')->execute(array($name,$gp,cr_now(),$org,$gid));}$rev=cr_revision($org);cr_ok(array('data'=>array('updated'=>1,'revision'=>$rev),'updated'=>1,'revision'=>$rev));}
 if($api==='student_photo'){if($_SERVER['REQUEST_METHOD']!=='POST')cr_err('POST gerekli.',405);if(!cr_can_edit())cr_err('Fotoğraf güncelleme yetkiniz yok.',403);$in=cr_body();$sid=(int)(isset($in['student_id'])?$in['student_id']:0);$b64=isset($in['photo_base64'])?(string)$in['photo_base64']:'';if(!$sid||$b64==='')cr_err('Öğrenci ve fotoğraf zorunludur.',400);if(strlen($b64)>8*1024*1024)cr_err('Fotoğraf çok büyük.',400);$bin=base64_decode($b64,true);if($bin===false||strlen($bin)>5*1024*1024)cr_err('Fotoğraf verisi geçersiz veya 5 MB sınırını aşıyor.',400);$tmp=tempnam(sys_get_temp_dir(),'elakrehber_');if($tmp===false)cr_err('Geçici dosya oluşturulamadı.',500);file_put_contents($tmp,$bin,LOCK_EX);$info=cr_photo_info($tmp);if(!$info){@unlink($tmp);cr_err('Yalnız JPG veya PNG fotoğraf desteklenir.',400);}$q=elak_db()->prepare('SELECT school_no,photo_path FROM `'.elak_table('data_students').'` WHERE org_id=? AND id=? AND active=1 LIMIT 1');$q->execute(array($org,$sid));$s=$q->fetch();if(!$s){@unlink($tmp);cr_err('Öğrenci bulunamadı.',404);}$safe=preg_replace('/[^A-Za-z0-9_-]+/','_',cr_clean($s['school_no'],40));$dir=cr_photo_dir($org);$rel=$org.'/'.$safe.'.'.$info['ext'];$abs=cr_photo_abs($rel);if(!@copy($tmp,$abs)){@unlink($tmp);cr_err('Fotoğraf kaydedilemedi.',500);}@unlink($tmp);@chmod($abs,0644);if(!empty($s['photo_path'])&&$s['photo_path']!==$rel){$old=cr_photo_abs($s['photo_path']);if(is_file($old))@unlink($old);}elak_db()->prepare('UPDATE `'.elak_table('data_students').'` SET photo_path=?,photo_updated_at=?,updated_at=? WHERE org_id=? AND id=?')->execute(array($rel,cr_now(),cr_now(),$org,$sid));$rev=cr_revision($org);cr_ok(array('data'=>array('updated'=>1,'photo_version'=>(int)$rev),'updated'=>1,'photo_version'=>(int)$rev));}
 if($api==='photo'){$sid=(int)(isset($_GET['id'])?$_GET['id']:0);$q=elak_db()->prepare('SELECT photo_path FROM `'.elak_table('data_students').'` WHERE org_id=? AND id=? AND active=1 LIMIT 1');$q->execute(array($org,$sid));$rel=$q->fetchColumn();if(!$rel)cr_err('Fotoğraf bulunamadı.',404);$abs=cr_photo_abs($rel);if(!is_file($abs))cr_err('Fotoğraf bulunamadı.',404);$info=cr_photo_info($abs);if(!$info)cr_err('Fotoğraf geçersiz.',404);header_remove('Content-Type');header('Content-Type: '.$info['mime']);header('Cache-Control: private, max-age=86400');header('X-Content-Type-Options: nosniff');readfile($abs);exit;}
 if($api==='web_sso')cr_err('Web yönetimi artık Kurum Yönetimi > Kurum Veri Merkezi üzerinden yapılır.',410);
 cr_err('Bilinmeyen işlem.',404);
}catch(Exception $e){error_log('ELAK core rehber: '.$e->getMessage());cr_err('Rehber işlemi tamamlanamadı: '.$e->getMessage(),500);}
