<?php
/* ELAK CORE Mobile Push API 0.9.3.1 - PHP 5.6+ */
error_reporting(E_ALL); ini_set('display_errors','0'); ini_set('log_errors','1');
header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache'); header('X-Content-Type-Options: nosniff');
require dirname(__FILE__).'/db.php';

function mp_https(){return (!empty($_SERVER['HTTPS'])&&strtolower($_SERVER['HTTPS'])!=='off')||(!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])&&strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])==='https');}
session_name('ELAKCORESESSID'); session_set_cookie_params(0,'/','',mp_https(),true); session_start();
function mp_now(){return date('Y-m-d H:i:s');}
function mp_csrf(){return isset($_SESSION['csrf'])?(string)$_SESSION['csrf']:'';}
function mp_send($d,$s){http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function mp_ok($d){if(!is_array($d))$d=array();$d['ok']=true;$d['csrf']=mp_csrf();mp_send($d,200);}
function mp_err($m,$s){mp_send(array('ok'=>false,'error'=>$m,'csrf'=>mp_csrf()),$s);}
function mp_body(){$r=file_get_contents('php://input');if($r===false||trim($r)==='')return array();$d=json_decode($r,true);if(!is_array($d))mp_err('Geçersiz istek verisi.',400);return $d;}
function mp_post(){if($_SERVER['REQUEST_METHOD']!=='POST')mp_err('Bu işlem POST isteği gerektirir.',405);}
function mp_csrf_check(){$sent=isset($_SERVER['HTTP_X_CSRF_TOKEN'])?(string)$_SERVER['HTTP_X_CSRF_TOKEN']:'';$cur=mp_csrf();if($cur===''||$sent===''||!hash_equals($cur,$sent))mp_err('Güvenlik doğrulaması başarısız.',403);}
function mp_clean($v,$n){$v=trim((string)$v);return function_exists('mb_substr')?mb_substr($v,0,$n,'UTF-8'):substr($v,0,$n);}
function mp_permissions(){return isset($_SESSION['permissions'])&&is_array($_SESSION['permissions'])?$_SESSION['permissions']:array();}
function mp_hasperm($k){if(!empty($_SESSION['legacy_org_admin']))return true;$p=mp_permissions();return !empty($p['*'])||!empty($p[$k]);}
function mp_org(){if(empty($_SESSION['org_id']))mp_err('Kurum oturumu gerekli.',401);$id=(int)$_SESSION['org_id'];$q=elak_db()->prepare('SELECT id,status,expiry,org_code,org_name FROM `'.elak_table('organizations').'` WHERE id=? LIMIT 1');$q->execute(array($id));$r=$q->fetch();if(!$r||empty($r['status'])||empty($r['expiry'])||strtotime($r['expiry'])<time())mp_err('Kurum oturumu geçersiz veya lisans süresi dolmuş.',401);return $r;}
function mp_user_id(){return !empty($_SESSION['user_id'])?(int)$_SESSION['user_id']:null;}
function mp_role(){return isset($_SESSION['role_key'])?mp_clean($_SESSION['role_key'],40):'admin';}

function mp_schema(){
 $db=elak_db();$d=elak_table('mobile_devices');$n=elak_table('mobile_notifications');$r=elak_table('mobile_receipts');$q=elak_table('mobile_push_queue');$c=elak_table('mobile_user_classes');
 $db->exec("CREATE TABLE IF NOT EXISTS `$d` (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,org_id INT NOT NULL,user_id INT NULL,role_key VARCHAR(40) NOT NULL,device_id VARCHAR(128) NOT NULL,fcm_token VARCHAR(512) NOT NULL,platform VARCHAR(20) NOT NULL DEFAULT 'android',app_version VARCHAR(40) NULL,active TINYINT(1) NOT NULL DEFAULT 1,last_seen DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_org_device(org_id,device_id),KEY idx_org_user(org_id,user_id),KEY idx_org_role(org_id,role_key),KEY idx_active(org_id,active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE IF NOT EXISTS `$n` (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,org_id INT NOT NULL,title VARCHAR(180) NOT NULL,body TEXT NOT NULL,level VARCHAR(20) NOT NULL DEFAULT 'info',target_type VARCHAR(20) NOT NULL DEFAULT 'school',target_value VARCHAR(190) NULL,created_by_user_id INT NULL,created_at DATETIME NOT NULL,expires_at DATETIME NULL,PRIMARY KEY(id),KEY idx_org_created(org_id,id),KEY idx_target(org_id,target_type,target_value)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE IF NOT EXISTS `$r` (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,notification_id BIGINT UNSIGNED NOT NULL,device_row_id BIGINT UNSIGNED NOT NULL,user_id INT NULL,delivered_at DATETIME NULL,read_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_receipt(notification_id,device_row_id),KEY idx_notification(notification_id),KEY idx_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE IF NOT EXISTS `$q` (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,notification_id BIGINT UNSIGNED NOT NULL,device_row_id BIGINT UNSIGNED NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'pending',attempts INT NOT NULL DEFAULT 0,last_error VARCHAR(500) NULL,sent_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_queue(notification_id,device_row_id),KEY idx_pending(status,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
 $db->exec("CREATE TABLE IF NOT EXISTS `$c` (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,org_id INT NOT NULL,user_id INT NOT NULL,class_key VARCHAR(80) NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_user_class(org_id,user_id,class_key),KEY idx_class(org_id,class_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
}

function mp_b64url($s){return rtrim(strtr(base64_encode($s),'+/','-_'),'=');}
function mp_firebase_credentials(){
 $cfg=elak_config();$path=isset($cfg['firebase_service_account_file'])?trim((string)$cfg['firebase_service_account_file']):'';
 if($path==='')return null;if($path[0]!=='/'&&preg_match('/^[A-Za-z]:[\\\\\/]/',$path)!==1)$path=dirname(__FILE__).'/'.$path;
 if(!is_file($path)||!is_readable($path))return null;$raw=file_get_contents($path);$j=json_decode($raw,true);if(!is_array($j)||empty($j['project_id'])||empty($j['client_email'])||empty($j['private_key']))return null;return $j;
}
function mp_fcm_token(){
 static $token=null;if($token!==null)return $token;$sa=mp_firebase_credentials();if(!$sa)return null;
 $now=time();$head=mp_b64url(json_encode(array('alg'=>'RS256','typ'=>'JWT')));$claims=mp_b64url(json_encode(array('iss'=>$sa['client_email'],'scope'=>'https://www.googleapis.com/auth/firebase.messaging','aud'=>'https://oauth2.googleapis.com/token','iat'=>$now,'exp'=>$now+3500)));
 $data=$head.'.'.$claims;$sig='';if(!openssl_sign($data,$sig,$sa['private_key'],OPENSSL_ALGO_SHA256))return null;$jwt=$data.'.'.mp_b64url($sig);
 if(!function_exists('curl_init'))return null;$ch=curl_init('https://oauth2.googleapis.com/token');curl_setopt_array($ch,array(CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>10,CURLOPT_HTTPHEADER=>array('Content-Type: application/x-www-form-urlencoded'),CURLOPT_POSTFIELDS=>http_build_query(array('grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt))));$resp=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($code<200||$code>=300)return null;$j=json_decode($resp,true);if(!is_array($j)||empty($j['access_token']))return null;$token=$j['access_token'];return $token;
}
function mp_dispatch($orgId,$limit){
 $access=mp_fcm_token();$sa=mp_firebase_credentials();if(!$access||!$sa||!function_exists('curl_multi_init'))return array('configured'=>false,'sent'=>0,'failed'=>0);
 $db=elak_db();$qt=elak_table('mobile_push_queue');$dt=elak_table('mobile_devices');$nt=elak_table('mobile_notifications');$sql='SELECT q.id qid,q.device_row_id,d.fcm_token,n.id nid,n.title,n.body,n.level,n.created_at FROM `'.$qt.'` q INNER JOIN `'.$dt.'` d ON d.id=q.device_row_id INNER JOIN `'.$nt.'` n ON n.id=q.notification_id WHERE q.status=\'pending\' AND d.active=1 AND n.org_id=? ORDER BY q.id ASC LIMIT '.(int)$limit;$st=$db->prepare($sql);$st->execute(array((int)$orgId));$rows=$st->fetchAll();if(!$rows)return array('configured'=>true,'sent'=>0,'failed'=>0);
 $mh=curl_multi_init();$handles=array();$url='https://fcm.googleapis.com/v1/projects/'.rawurlencode($sa['project_id']).'/messages:send';foreach($rows as $row){$payload=array('message'=>array('token'=>$row['fcm_token'],'notification'=>array('title'=>$row['title'],'body'=>$row['body']),'data'=>array('notification_id'=>(string)$row['nid'],'title'=>(string)$row['title'],'body'=>(string)$row['body'],'level'=>(string)$row['level'],'created_at'=>(string)$row['created_at']),'android'=>array('priority'=>'high','notification'=>array('channel_id'=>'elak_school_updates','sound'=>'default'))));$ch=curl_init($url);curl_setopt_array($ch,array(CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>4,CURLOPT_TIMEOUT=>12,CURLOPT_HTTPHEADER=>array('Authorization: Bearer '.$access,'Content-Type: application/json'),CURLOPT_POSTFIELDS=>json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)));curl_multi_add_handle($mh,$ch);$handles[(int)$ch]=array($ch,$row);}
 $running=null;do{$mrc=curl_multi_exec($mh,$running);if($running)curl_multi_select($mh,1.0);}while($running&&$mrc==CURLM_OK);$sent=0;$failed=0;$now=mp_now();foreach($handles as $pair){$ch=$pair[0];$row=$pair[1];$resp=curl_multi_getcontent($ch);$code=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$ok=$code>=200&&$code<300;if($ok){$u=$db->prepare('UPDATE `'.$qt.'` SET status=\'sent\',attempts=attempts+1,last_error=NULL,sent_at=?,updated_at=? WHERE id=?');$u->execute(array($now,$now,(int)$row['qid']));$sent++;}else{$msg=mp_clean($resp,480);$status=(strpos($resp,'UNREGISTERED')!==false||strpos($resp,'registration-token-not-registered')!==false)?'dead':'pending';$u=$db->prepare('UPDATE `'.$qt.'` SET status=?,attempts=attempts+1,last_error=?,updated_at=? WHERE id=?');$u->execute(array($status,$msg,$now,(int)$row['qid']));if($status==='dead'){$db->prepare('UPDATE `'.$dt.'` SET active=0,updated_at=? WHERE id=?')->execute(array($now,(int)$row['device_row_id']));}$failed++;}curl_multi_remove_handle($mh,$ch);curl_close($ch);}curl_multi_close($mh);return array('configured'=>true,'sent'=>$sent,'failed'=>$failed);
}
function mp_worker_authorized(){if(PHP_SAPI==='cli')return true;$cfg=elak_config();$expected=isset($cfg['push_worker_key'])?(string)$cfg['push_worker_key']:'';$sent=isset($_SERVER['HTTP_X_ELAK_PUSH_KEY'])?(string)$_SERVER['HTTP_X_ELAK_PUSH_KEY']:'';return $expected!==''&&$sent!==''&&hash_equals($expected,$sent);}

mp_schema();
$action=isset($_GET['action'])?$_GET['action']:'status';
if($action==='worker'){if(!mp_worker_authorized())mp_err('Yetkisiz worker çağrısı.',403);$org=isset($_GET['org'])?(int)$_GET['org']:0;$limit=isset($_GET['limit'])?max(1,min(200,(int)$_GET['limit'])):100;if($org>0){mp_ok(mp_dispatch($org,$limit));}$q=elak_db()->query('SELECT DISTINCT n.org_id FROM `'.elak_table('mobile_push_queue').'` q INNER JOIN `'.elak_table('mobile_notifications').'` n ON n.id=q.notification_id WHERE q.status=\'pending\' LIMIT 20');$out=array('configured'=>mp_firebase_credentials()?true:false,'sent'=>0,'failed'=>0);foreach($q->fetchAll() as $rr){$x=mp_dispatch((int)$rr['org_id'],$limit);$out['sent']+=$x['sent'];$out['failed']+=$x['failed'];}$out['configured']=mp_firebase_credentials()?true:false;mp_ok($out);}

$org=mp_org();$orgId=(int)$org['id'];$uid=mp_user_id();$role=mp_role();
if($action==='status'){mp_ok(array('service'=>'ELAK Mobile Push','version'=>'0.9.3.1','firebase_configured'=>mp_firebase_credentials()?true:false));}

if($action==='device_register'){
 mp_post();mp_csrf_check();$in=mp_body();$device=mp_clean(isset($in['device_id'])?$in['device_id']:'',128);$token=mp_clean(isset($in['fcm_token'])?$in['fcm_token']:'',512);$ver=mp_clean(isset($in['app_version'])?$in['app_version']:'',40);if($device===''||$token==='')mp_err('Cihaz veya FCM token bilgisi eksik.',400);$t=elak_table('mobile_devices');$now=mp_now();$q=elak_db()->prepare('SELECT id FROM `'.$t.'` WHERE org_id=? AND device_id=? LIMIT 1');$q->execute(array($orgId,$device));$r=$q->fetch();if($r){$u=elak_db()->prepare('UPDATE `'.$t.'` SET user_id=?,role_key=?,fcm_token=?,platform=\'android\',app_version=?,active=1,last_seen=?,updated_at=? WHERE id=?');$u->execute(array($uid,$role,$token,$ver,$now,$now,(int)$r['id']));$id=(int)$r['id'];}else{$u=elak_db()->prepare('INSERT INTO `'.$t.'` (org_id,user_id,role_key,device_id,fcm_token,platform,app_version,active,last_seen,created_at,updated_at) VALUES (?,?,?,?,?,\'android\',?,1,?,?,?)');$u->execute(array($orgId,$uid,$role,$device,$token,$ver,$now,$now,$now));$id=(int)elak_db()->lastInsertId();}mp_ok(array('device_row_id'=>$id));
}

if($action==='notification_list'){
 if(!mp_hasperm('announcements.view')&&!mp_hasperm('dashboard.view'))mp_err('Bu işlem için yetkiniz yok.',403);$items=array();$nt=elak_table('mobile_notifications');$params=array($orgId,$role);$where='org_id=? AND (expires_at IS NULL OR expires_at>=NOW()) AND (target_type=\'school\' OR (target_type=\'role\' AND target_value=?)';if($uid!==null){$where.=' OR (target_type=\'user\' AND target_value=?) OR (target_type=\'class\' AND target_value IN (SELECT class_key FROM `'.elak_table('mobile_user_classes').'` WHERE org_id=? AND user_id=?))';$params[]=(string)$uid;$params[]=$orgId;$params[]=$uid;}$where.=')';$q=elak_db()->prepare('SELECT id,title,body,level,created_at FROM `'.$nt.'` WHERE '.$where.' ORDER BY id DESC LIMIT 100');$q->execute($params);foreach($q->fetchAll() as $r){$r['source']='push';$items[]=$r;}
 $now=mp_now();$a=elak_db()->prepare('SELECT id,title,body,level,created_at FROM `'.elak_table('announcements').'` WHERE active=1 AND (org_id IS NULL OR org_id=?) AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>=?) ORDER BY id DESC LIMIT 25');$a->execute(array($orgId,$now,$now));foreach($a->fetchAll() as $r){$r['id']=-1*(int)$r['id'];$r['source']='announcement';$items[]=$r;}usort($items,function($a,$b){return strcmp($b['created_at'],$a['created_at']);});if(count($items)>100)$items=array_slice($items,0,100);mp_ok(array('notifications'=>$items));
}

if($action==='notification_ack'){
 mp_post();mp_csrf_check();$in=mp_body();$nid=(int)(isset($in['notification_id'])?$in['notification_id']:0);$device=mp_clean(isset($in['device_id'])?$in['device_id']:'',128);$state=mp_clean(isset($in['state'])?$in['state']:'delivered',20);if($nid<=0||$device==='')mp_err('Bildirim veya cihaz bilgisi eksik.',400);if($state!=='delivered'&&$state!=='read')mp_err('Geçersiz bildirim durumu.',400);$d=elak_db()->prepare('SELECT id,user_id FROM `'.elak_table('mobile_devices').'` WHERE org_id=? AND device_id=? AND active=1 LIMIT 1');$d->execute(array($orgId,$device));$dev=$d->fetch();if(!$dev)mp_err('Cihaz kaydı bulunamadı.',404);$n=elak_db()->prepare('SELECT id FROM `'.elak_table('mobile_notifications').'` WHERE id=? AND org_id=? LIMIT 1');$n->execute(array($nid,$orgId));if(!$n->fetch())mp_err('Bildirim bulunamadı.',404);$rt=elak_table('mobile_receipts');$q=elak_db()->prepare('SELECT id FROM `'.$rt.'` WHERE notification_id=? AND device_row_id=? LIMIT 1');$q->execute(array($nid,(int)$dev['id']));$old=$q->fetch();$now=mp_now();if($old){if($state==='read'){$u=elak_db()->prepare('UPDATE `'.$rt.'` SET delivered_at=COALESCE(delivered_at,?),read_at=COALESCE(read_at,?) WHERE id=?');$u->execute(array($now,$now,(int)$old['id']));}else{$u=elak_db()->prepare('UPDATE `'.$rt.'` SET delivered_at=COALESCE(delivered_at,?) WHERE id=?');$u->execute(array($now,(int)$old['id']));}}else{$u=elak_db()->prepare('INSERT INTO `'.$rt.'` (notification_id,device_row_id,user_id,delivered_at,read_at) VALUES (?,?,?,?,?)');$u->execute(array($nid,(int)$dev['id'],$uid,$now,$state==='read'?$now:null));}mp_ok(array());
}

if($action==='notification_send'){
 mp_post();mp_csrf_check();if(!mp_hasperm('announcements.manage'))mp_err('Bildirim gönderme yetkiniz yok.',403);$in=mp_body();$title=mp_clean(isset($in['title'])?$in['title']:'',180);$body=mp_clean(isset($in['body'])?$in['body']:'',8000);$level=mp_clean(isset($in['level'])?$in['level']:'info',20);$type=mp_clean(isset($in['target_type'])?$in['target_type']:'school',20);$value=mp_clean(isset($in['target_value'])?$in['target_value']:'',190);if($title===''||$body==='')mp_err('Başlık ve bildirim metni zorunludur.',400);if(!in_array($type,array('school','role','user','class'),true))mp_err('Geçersiz hedef türü.',400);if($type!=='school'&&$value==='')mp_err('Hedef değeri gerekli.',400);if($type==='role'){$x=elak_db()->prepare('SELECT id FROM `'.elak_table('roles').'` WHERE org_id=? AND role_key=? LIMIT 1');$x->execute(array($orgId,$value));if(!$x->fetch())mp_err('Rol bulunamadı.',404);}if($type==='user'){$x=elak_db()->prepare('SELECT id FROM `'.elak_table('users').'` WHERE org_id=? AND id=? AND active=1 LIMIT 1');$x->execute(array($orgId,(int)$value));if(!$x->fetch())mp_err('Kullanıcı bulunamadı.',404);$value=(string)(int)$value;}$now=mp_now();$nt=elak_table('mobile_notifications');$u=elak_db()->prepare('INSERT INTO `'.$nt.'` (org_id,title,body,level,target_type,target_value,created_by_user_id,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,NULL)');$u->execute(array($orgId,$title,$body,$level,$type,$type==='school'?null:$value,$uid,$now));$nid=(int)elak_db()->lastInsertId();$dt=elak_table('mobile_devices');if($type==='school'){$sql='SELECT id FROM `'.$dt.'` WHERE org_id=? AND active=1';$p=array($orgId);}elseif($type==='role'){$sql='SELECT id FROM `'.$dt.'` WHERE org_id=? AND active=1 AND role_key=?';$p=array($orgId,$value);}elseif($type==='user'){$sql='SELECT id FROM `'.$dt.'` WHERE org_id=? AND active=1 AND user_id=?';$p=array($orgId,(int)$value);}else{$sql='SELECT DISTINCT d.id FROM `'.$dt.'` d INNER JOIN `'.elak_table('mobile_user_classes').'` c ON c.org_id=d.org_id AND c.user_id=d.user_id WHERE d.org_id=? AND d.active=1 AND c.class_key=?';$p=array($orgId,$value);}$x=elak_db()->prepare($sql);$x->execute($p);$ids=$x->fetchAll();$qt=elak_table('mobile_push_queue');$ins=elak_db()->prepare('INSERT IGNORE INTO `'.$qt.'` (notification_id,device_row_id,status,attempts,created_at,updated_at) VALUES (?,?,\'pending\',0,?,?)');foreach($ids as $rr)$ins->execute(array($nid,(int)$rr['id'],$now,$now));$dispatch=count($ids)<=40?mp_dispatch($orgId,40):array('configured'=>mp_firebase_credentials()?true:false,'sent'=>0,'failed'=>0);mp_ok(array('id'=>$nid,'queued'=>count($ids),'dispatch'=>$dispatch));
}

if($action==='notification_report'){
 if(!mp_hasperm('announcements.manage')&&!mp_hasperm('reports.view'))mp_err('Rapor yetkiniz yok.',403);$nt=elak_table('mobile_notifications');$qt=elak_table('mobile_push_queue');$rt=elak_table('mobile_receipts');$sql='SELECT n.id,n.title,n.target_type,n.target_value,n.created_at,(SELECT COUNT(*) FROM `'.$qt.'` q WHERE q.notification_id=n.id) target_count,(SELECT COUNT(*) FROM `'.$qt.'` q WHERE q.notification_id=n.id AND q.status=\'sent\') accepted_count,(SELECT COUNT(*) FROM `'.$rt.'` r WHERE r.notification_id=n.id AND r.delivered_at IS NOT NULL) delivered_count,(SELECT COUNT(*) FROM `'.$rt.'` r WHERE r.notification_id=n.id AND r.read_at IS NOT NULL) read_count FROM `'.$nt.'` n WHERE n.org_id=? ORDER BY n.id DESC LIMIT 100';$q=elak_db()->prepare($sql);$q->execute(array($orgId));mp_ok(array('reports'=>$q->fetchAll()));
}

if($action==='class_members_save'){
 mp_post();mp_csrf_check();if(!mp_hasperm('users.manage'))mp_err('Sınıf eşleştirme yetkiniz yok.',403);$in=mp_body();$userId=(int)(isset($in['user_id'])?$in['user_id']:0);$classes=isset($in['classes'])&&is_array($in['classes'])?$in['classes']:array();$u=elak_db()->prepare('SELECT id FROM `'.elak_table('users').'` WHERE org_id=? AND id=? LIMIT 1');$u->execute(array($orgId,$userId));if(!$u->fetch())mp_err('Kullanıcı bulunamadı.',404);$ct=elak_table('mobile_user_classes');elak_db()->prepare('DELETE FROM `'.$ct.'` WHERE org_id=? AND user_id=?')->execute(array($orgId,$userId));$ins=elak_db()->prepare('INSERT IGNORE INTO `'.$ct.'` (org_id,user_id,class_key,created_at) VALUES (?,?,?,?)');foreach($classes as $ck){$ck=mp_clean($ck,80);if($ck!=='')$ins->execute(array($orgId,$userId,$ck,mp_now()));}mp_ok(array());
}

mp_err('Bilinmeyen işlem.',404);
