<?php
/* ELAK Okulum Push Yönetimi 0.9.3.1 - mevcut ELAK CORE oturumu ile çalışır */
?><!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ELAK • Bildirim Yönetimi</title>
<style>
:root{--navy:#091e42;--blue:#2563eb;--green:#059669;--red:#dc2626;--bg:#f3f6fb;--ink:#10213d;--muted:#64748b;--line:#dfe7f2}
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--ink)}
.top{background:linear-gradient(135deg,#091e42,#123d73);color:#fff;padding:20px}.topin{max-width:1120px;margin:auto;display:flex;justify-content:space-between;gap:20px;align-items:center}.brand b{font-size:22px}.brand small{display:block;color:#c7d8ef;margin-top:4px}.back{color:#fff;text-decoration:none;border:1px solid #ffffff44;border-radius:12px;padding:9px 12px}
.wrap{max-width:1120px;margin:18px auto;padding:0 14px}.grid{display:grid;grid-template-columns:minmax(0,420px) minmax(0,1fr);gap:16px}@media(max-width:850px){.grid{grid-template-columns:1fr}}
.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 4px 18px #17345a0d}.card h2{margin:0 0 4px;font-size:18px}.sub{color:var(--muted);font-size:12px;margin-bottom:16px}
label{display:block;font-size:12px;font-weight:700;margin:11px 0 5px}input,select,textarea{width:100%;border:1px solid #cfd9e7;border-radius:11px;padding:11px 12px;background:#fff;font:inherit;color:var(--ink)}textarea{min-height:130px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:9px}.btn{border:0;border-radius:12px;padding:12px 14px;font-weight:800;cursor:pointer;background:var(--blue);color:#fff;width:100%;margin-top:14px}.btn:disabled{opacity:.55;cursor:wait}.msg{margin-top:10px;font-size:12px;min-height:18px}.ok{color:var(--green)}.err{color:var(--red)}
.status{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0 15px}.stat{background:#f7f9fd;border:1px solid var(--line);border-radius:12px;padding:10px;text-align:center}.stat b{display:block;font-size:19px}.stat small{font-size:10px;color:var(--muted)}
.tablewrap{overflow:auto;border:1px solid var(--line);border-radius:13px}table{border-collapse:collapse;width:100%;min-width:690px}th,td{padding:10px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px}th{background:#f7f9fc;color:#53657c;position:sticky;top:0}.badge{display:inline-block;padding:4px 7px;border-radius:999px;background:#e8eef8;font-size:10px;font-weight:800}.empty{color:var(--muted);padding:24px;text-align:center}.hint{font-size:11px;color:var(--muted);background:#f8fafc;border:1px solid var(--line);padding:10px;border-radius:11px;margin-top:8px}
</style></head><body>
<div class="top"><div class="topin"><div class="brand"><b>ELAK • Bildirim Yönetimi</b><small id="school">Kurum doğrulanıyor…</small></div><a class="back" href="./">Ana Panele Dön</a></div></div>
<div class="wrap"><div class="grid">
<section class="card"><h2>Yeni Bildirim</h2><div class="sub">Okul, rol, kullanıcı veya sınıf bazında gönderim</div>
<label>Başlık</label><input id="title" maxlength="180" placeholder="Örn. Yarınki DYK Programı">
<label>Bildirim Metni</label><textarea id="body" maxlength="8000" placeholder="Gönderilecek bilgilendirme…"></textarea>
<div class="row"><div><label>Önem Düzeyi</label><select id="level"><option value="info">Bilgi</option><option value="success">Olumlu</option><option value="warning">Uyarı</option><option value="danger">Kritik</option></select></div><div><label>Hedef</label><select id="targetType" onchange="targetChanged()"><option value="school">Tüm Okul</option><option value="role">Rol</option><option value="user">Tek Kullanıcı</option><option value="class">Sınıf</option></select></div></div>
<div id="targetBox" style="display:none"><label id="targetLabel">Hedef Değeri</label><select id="targetSelect" style="display:none"></select><input id="targetInput" style="display:none"></div>
<div class="hint" id="targetHint">Tüm kayıtlı okul cihazlarına gönderilir.</div>
<button class="btn" id="sendBtn" onclick="sendNotification()">Bildirimi Gönder</button><div class="msg" id="sendMsg"></div>
</section>
<section class="card"><h2>Teslim / Okundu Raporu</h2><div class="sub">FCM kabulü, gerçek cihaz teslimi ve kullanıcı okuması ayrı izlenir.</div>
<div class="status"><div class="stat"><b id="sTotal">0</b><small>HEDEF CİHAZ</small></div><div class="stat"><b id="sSent">0</b><small>FCM KABUL</small></div><div class="stat"><b id="sDelivered">0</b><small>TESLİM</small></div><div class="stat"><b id="sRead">0</b><small>OKUNDU</small></div></div>
<div class="tablewrap"><table><thead><tr><th>Bildirim</th><th>Hedef</th><th>Cihaz</th><th>FCM</th><th>Teslim</th><th>Okundu</th><th>Tarih</th></tr></thead><tbody id="reportRows"><tr><td colspan="7" class="empty">Yükleniyor…</td></tr></tbody></table></div>
</section></div></div>
<script>
let csrf='',currentUser=null,users=[],roles=[];
async function req(url,opt={}){opt.credentials='same-origin';opt.headers=Object.assign({'Accept':'application/json'},opt.headers||{});if(opt.body&&typeof opt.body!=='string'){opt.headers['Content-Type']='application/json';opt.headers['X-CSRF-Token']=csrf;opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt),j=await r.json().catch(()=>({ok:false,error:'Geçersiz sunucu yanıtı'}));if(j.csrf)csrf=j.csrf;if(!r.ok||j.ok===false)throw new Error(j.error||('HTTP '+r.status));return j}
async function init(){try{const b=await req('api.php?action=bootstrap');if(!b.license||!b.user)throw new Error('Önce ELAK kurum panelinde oturum açın.');csrf=b.csrf||'';currentUser=b.user;document.getElementById('school').textContent=(b.license.org_name||b.license.org_code)+' • '+(b.user.full_name||'Kullanıcı');const p=b.user.permissions||{},full=b.user.legacy||p['*'];if(!(full||p['announcements.manage']))throw new Error('Bu hesapta bildirim gönderme yetkisi yok.');try{const u=await req('api.php?action=users_list');users=u.users||[]}catch(e){}try{const r=await req('api.php?action=roles_list');roles=r.roles||[]}catch(e){}targetChanged();await reports()}catch(e){document.getElementById('sendMsg').className='msg err';document.getElementById('sendMsg').textContent=e.message;document.getElementById('sendBtn').disabled=true;document.getElementById('reportRows').innerHTML='<tr><td colspan="7" class="empty">'+esc(e.message)+'</td></tr>'}}
function targetChanged(){const type=document.getElementById('targetType').value,box=document.getElementById('targetBox'),sel=document.getElementById('targetSelect'),inp=document.getElementById('targetInput'),lab=document.getElementById('targetLabel'),hint=document.getElementById('targetHint');box.style.display=type==='school'?'none':'block';sel.style.display='none';inp.style.display='none';sel.innerHTML='';inp.value='';if(type==='school'){hint.textContent='Tüm kayıtlı okul cihazlarına gönderilir.';return}if(type==='role'){lab.textContent='Rol';sel.style.display='block';(roles.length?roles:[{role_key:'teacher',role_name:'Öğretmen'},{role_key:'parent',role_name:'Veli'},{role_key:'security',role_name:'Güvenlik'}]).forEach(r=>sel.add(new Option(r.role_name||r.role_key,r.role_key)));hint.textContent='Yalnız seçilen roldeki kayıtlı cihazlara gider.'}else if(type==='user'){lab.textContent='Kullanıcı';sel.style.display='block';users.forEach(u=>sel.add(new Option((u.full_name||u.username)+' • '+(u.role_name||u.role_key),u.id)));if(!users.length){sel.add(new Option('Kullanıcı listesi yetkisi yok — ID girin',''));sel.style.display='none';inp.style.display='block';inp.placeholder='ELAK kullanıcı ID';}hint.textContent='Tek kullanıcıya bağlı tüm aktif cihazlara gider.'}else{lab.textContent='Sınıf Anahtarı';inp.style.display='block';inp.placeholder='Örn. 8/A';hint.textContent='Sınıf eşleşmesi sunucuda tanımlı kullanıcılara gönderilir.'}}
async function sendNotification(){const btn=document.getElementById('sendBtn'),msg=document.getElementById('sendMsg'),type=document.getElementById('targetType').value;let value='';if(type!=='school'){value=document.getElementById('targetSelect').style.display!=='none'?document.getElementById('targetSelect').value:document.getElementById('targetInput').value.trim()}const data={title:document.getElementById('title').value.trim(),body:document.getElementById('body').value.trim(),level:document.getElementById('level').value,target_type:type,target_value:value};if(!data.title||!data.body){msg.className='msg err';msg.textContent='Başlık ve metin zorunludur.';return}btn.disabled=true;msg.className='msg';msg.textContent='Gönderim hazırlanıyor…';try{const r=await req('mobile-push.php?action=notification_send',{method:'POST',body:data});msg.className='msg ok';msg.textContent='Bildirim oluşturuldu. '+(r.queued||0)+' cihaz kuyruğa alındı.';document.getElementById('title').value='';document.getElementById('body').value='';await reports()}catch(e){msg.className='msg err';msg.textContent=e.message}finally{btn.disabled=false}}
async function reports(){const r=await req('mobile-push.php?action=notification_report');const rows=r.reports||[];let t=0,s=0,d=0,rd=0;rows.forEach(x=>{t+=+x.target_count||0;s+=+x.accepted_count||0;d+=+x.delivered_count||0;rd+=+x.read_count||0});document.getElementById('sTotal').textContent=t;document.getElementById('sSent').textContent=s;document.getElementById('sDelivered').textContent=d;document.getElementById('sRead').textContent=rd;document.getElementById('reportRows').innerHTML=rows.length?rows.map(x=>'<tr><td><b>'+esc(x.title)+'</b></td><td><span class="badge">'+esc(targetText(x))+'</span></td><td>'+x.target_count+'</td><td>'+x.accepted_count+'</td><td>'+x.delivered_count+'</td><td><b>'+x.read_count+'</b></td><td>'+esc(String(x.created_at||'').slice(0,16))+'</td></tr>').join(''):'<tr><td colspan="7" class="empty">Henüz mobil bildirim gönderilmedi.</td></tr>'}
function targetText(x){return x.target_type==='school'?'Tüm okul':x.target_type==='role'?'Rol: '+(x.target_value||''):x.target_type==='user'?'Kullanıcı: '+(x.target_value||''):'Sınıf: '+(x.target_value||'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
init();
</script></body></html>
